#端口
server:
  port: 10086
spring:
  application:
    name: tensquare-eureka  #服务id
#注册中心的配置
eureka:
  client:
    register-with-eureka: false #注册到eureka
    fetch-registry: false #拉取注册信息
    service-url:
      defaultZone: http://192.168.207.111:10086/eureka #注册中心的地址
  server: #服务端：配置【测试开发阶段】
    enable-self-preservation: true # 关闭自我保护
    #eviction-interval-timer-in-ms: 5000 # 每隔5秒进行一次服务列表清理