server: 
  port: 9010
spring: 
  application:  
    name: tensquare-user-spider #指定服务名
#redis的配置信息
  redis:
    host: 192.168.207.111
    port: 6379
#Eureka客户端配置
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
feign:
  hystrix:
    enabled: true # 开启Feign的熔断功能
tensquare-user:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
    ConnectTimeout: 1000 # Ribbon的连接超时时间
    ReadTimeout: 1000 # Ribbon的数据读取超时时间
    OkToRetryOnAllOperations: false # 是否对所有操作都进行重试
    MaxAutoRetriesNextServer: 1 # 切换实例的重试次数
#爬取url路径
article:
  http_path: http://www.cfei.net
user:
  save_path: D:/00_class/110/webmagic/tensquareimg/


